module Mcp
  module Tools
    class SshExportConfig < Base
      DESCRIPTION = "Export SSH configuration files (ssh_config and/or known_hosts format)."
      INPUT_SCHEMA = {
        type: "object",
        properties: {
          format: {
            type: "string",
            description: "Output format: 'ssh_config', 'known_hosts', or 'both'",
            enum: [ "ssh_config", "known_hosts", "both" ],
            default: "both"
          },
          connection_names: {
            type: "array",
            items: { type: "string" },
            description: "Optional list of connection names to export (default: all active connections)"
          },
          include_archived: {
            type: "boolean",
            description: "Include archived items (default: false)"
          }
        },
        required: []
      }.freeze

      def call(params)
        format = params[:format] || "both"
        include_archived = params[:include_archived] || false

        result = {}

        # Export SSH config (connections)
        if format == "ssh_config" || format == "both"
          result[:ssh_config] = generate_ssh_config(params[:connection_names], include_archived)
        end

        # Export known_hosts (server keys)
        if format == "known_hosts" || format == "both"
          result[:known_hosts] = generate_known_hosts(include_archived)
        end

        log_access(
          action: "mcp_export_ssh_config",
          details: { format: format, include_archived: include_archived }
        )

        success(result)
      end

      private

      def generate_ssh_config(connection_names, include_archived)
        connections = project.ssh_connections
        connections = include_archived ? connections : connections.active

        if connection_names.present?
          connections = connections.where(name: connection_names)
        end

        connections = connections.includes(:ssh_client_key, :jump_connection).order(:name)

        lines = [
          "# SSH Config generated by Vault",
          "# Project: #{project.name}",
          "# Generated: #{Time.current.iso8601}",
          ""
        ]

        connections.each do |conn|
          lines << conn.to_ssh_config
          lines << ""
        end

        {
          content: lines.join("\n"),
          connection_count: connections.count,
          instructions: "Save to ~/.ssh/config or include in your SSH config file"
        }
      end

      def generate_known_hosts(include_archived)
        server_keys = project.ssh_server_keys
        server_keys = include_archived ? server_keys : server_keys.active

        # Only include trusted keys by default
        server_keys = server_keys.trusted unless include_archived

        server_keys = server_keys.order(:hostname, :port)

        lines = [
          "# Known hosts generated by Vault",
          "# Project: #{project.name}",
          "# Generated: #{Time.current.iso8601}"
        ]

        server_keys.each do |key|
          lines << key.to_known_hosts_line
        end

        {
          content: lines.join("\n"),
          host_count: server_keys.count,
          instructions: "Append to ~/.ssh/known_hosts"
        }
      end
    end
  end
end
